# -*- coding: utf-8 -*-
"""Manipulasi String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1npnEEL6O2UnB2zKf0Tf_E0PAWM2-_jtW

**STRING**
"""

nama = 'Rafi'
print("--------------------------")
asal = "Indonesia"
print("--------------------------")
print(nama)
print("--------------------------")
print(asal)
print("--------------------------")
print(nama, asal)
print("--------------------------")
print("halo, nama saya", nama, "asal saya dari", asal)
print("--------------------------")
data_lengkap = nama + asal
print(data_lengkap)

"""**MANIPULASI STRING**"""



"""**STRING + NON STRING**"""

asal_kota = "Bandar Lampung"
kode_pos = 35144

asal_kota_kode_pos = asal_kota + str(kode_pos)
print(asal_kota_kode_pos)

asal_kota_x3 = asal_kota * 3
print(asal_kota_x3)